// <auto-generated />
using System;
using MiProyectoApi.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiProyectoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiProyectoApi.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            Date = new DateTime(2023, 9, 17, 17, 4, 23, 378, DateTimeKind.Local).AddTicks(2709),
                            Name = "Marcel",
                            Photo = "blablabla",
                            Surname = "Soto"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 2,
                            Date = new DateTime(2023, 9, 17, 17, 4, 23, 378, DateTimeKind.Local).AddTicks(2755),
                            Name = "Alberto",
                            Photo = "blablablaaaa",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 3,
                            Date = new DateTime(2023, 9, 17, 17, 4, 23, 378, DateTimeKind.Local).AddTicks(2758),
                            Name = "Manuel",
                            Photo = "blablablaaaaaa",
                            Surname = "Esquinso"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
